#!/usr/bin/env python3
"""
Orchestrate MolFormer embedding extraction via an external MolTran conda env.

DARTnet training calls ensure_embeddings(); missing .pt files are generated by
subprocess in MolTran_CUDA11 (or --molformer-env), matching the historical notebook.
"""

from __future__ import annotations

import argparse
import os
import shutil
import subprocess
from pathlib import Path
from typing import List, Optional, Sequence, Tuple

PREPROCESSING_DIR = Path(__file__).resolve().parent
ROOT = PREPROCESSING_DIR.parent
MOLTRAN_SCRIPT = PREPROCESSING_DIR / "extract_embeddings_moltran.py"
MOLFORMER_CODE_ROOT = PREPROCESSING_DIR / "molformer"
DEFAULT_HPARAMS = str(MOLFORMER_CODE_ROOT / "hparams.yaml")
DEFAULT_CKPT = str(
    PREPROCESSING_DIR / "checkpoints" / "N-Step-Checkpoint_3_30000.ckpt"
)
DEFAULT_MOLFORMER_ENV = "MolTran_CUDA11"

DEFAULT_TRAIN_DATASETS: Sequence[Tuple[str, str]] = (
    ("train_set.csv", "train_emb.pt"),
    ("val_set.csv", "val_emb.pt"),
    ("test_set.csv", "test_emb.pt"),
)


def get_molformer_code_root() -> Path:
    if not MOLFORMER_CODE_ROOT.is_dir():
        raise FileNotFoundError(f"MolFormer code not found: {MOLFORMER_CODE_ROOT}")
    return MOLFORMER_CODE_ROOT


def resolve_conda_python(env_name: str) -> str:
    """Resolve python executable for a conda environment name."""
    candidates = [
        Path.home() / "miniconda3/envs" / env_name / "bin/python",
        Path.home() / "anaconda3/envs" / env_name / "bin/python",
        Path(os.environ.get("CONDA_PREFIX", "")).parent / env_name / "bin/python",
    ]
    for path in candidates:
        if path.is_file():
            return str(path)

    conda = shutil.which("conda")
    if conda:
        result = subprocess.run(
            [conda, "run", "-n", env_name, "python", "-c", "import sys; print(sys.executable)"],
            check=False,
            capture_output=True,
            text=True,
        )
        if result.returncode == 0:
            python_path = result.stdout.strip().splitlines()[-1]
            if python_path and Path(python_path).is_file():
                return python_path

    searched = ", ".join(str(p) for p in candidates if str(p))
    raise FileNotFoundError(
        f"Could not find python for conda env '{env_name}'. Searched: {searched}"
    )


def _collect_pending(
    data_dir_path: Path,
    dataset_pairs: Sequence[Tuple[str, str]],
    skip_if_exists: bool,
) -> List[Tuple[Path, Path]]:
    pending: List[Tuple[Path, Path]] = []
    for csv_name, pt_name in dataset_pairs:
        csv_path = data_dir_path / csv_name
        pt_path = data_dir_path / pt_name
        if not csv_path.is_file():
            print(f"[Embedding] Skip: CSV not found {csv_path}")
            continue
        if skip_if_exists and pt_path.is_file():
            print(f"[Embedding] Exists, skip {pt_path}")
            continue
        pending.append((csv_path, pt_path))
    return pending


def _run_moltran_subprocess(
    *,
    molformer_env: str,
    data_dir: str,
    ckpt_path: str,
    hparams_path: str,
    device: str,
    batch_size: int,
    datasets: Sequence[Tuple[str, str]],
    skip_if_exists: bool,
) -> None:
    python_exe = resolve_conda_python(molformer_env)
    molformer_code_root = get_molformer_code_root()
    cmd = [
        python_exe,
        str(MOLTRAN_SCRIPT),
        "--data-dir",
        data_dir,
        "--ckpt-path",
        ckpt_path,
        "--hparams-path",
        hparams_path,
        "--device",
        device,
        "--batch-size",
        str(batch_size),
        "--datasets",
        *[f"{csv}:{pt}" for csv, pt in datasets],
    ]
    if not skip_if_exists:
        cmd.append("--no-skip-if-exists")

    print(f"[Embedding] Delegating to {molformer_env}: {' '.join(cmd)}")
    env = os.environ.copy()
    env["DART_EMBEDDING_SUBPROCESS"] = "1"
    subprocess.run(cmd, check=True, cwd=str(molformer_code_root), env=env)


def ensure_embeddings(
    data_dir: str,
    ckpt_path: str,
    hparams_path: Optional[str] = None,
    molformer_env: str = DEFAULT_MOLFORMER_ENV,
    device: str = "cuda",
    batch_size: int = 32,
    datasets: Optional[Sequence[Tuple[str, str]]] = None,
    skip_if_exists: bool = True,
) -> None:
    """Generate MolFormer embeddings next to input CSV files if missing."""
    if os.environ.get("DART_EMBEDDING_SUBPROCESS") == "1":
        raise RuntimeError(
            "ensure_embeddings must not be called recursively inside MolTran subprocess"
        )

    ckpt_path = ckpt_path or DEFAULT_CKPT
    hparams_path = hparams_path or DEFAULT_HPARAMS

    if device == "cuda" and not device.startswith("cuda:"):
        device = "cuda:0"

    data_dir_path = Path(data_dir)
    dataset_pairs = list(datasets or DEFAULT_TRAIN_DATASETS)
    pending = _collect_pending(data_dir_path, dataset_pairs, skip_if_exists)
    if not pending:
        return

    if not molformer_env:
        raise ValueError(
            "molformer_env is required: graph+fp+emb mode needs a MolTran conda env "
            "to generate embeddings consistent with the historical notebook."
        )

    pending_names = [pt.name for _, pt in pending]
    print(
        f"[Embedding] Generating {len(pending)} file(s) in {data_dir_path}: "
        f"{', '.join(pending_names)}"
    )
    _run_moltran_subprocess(
        molformer_env=molformer_env,
        data_dir=data_dir,
        ckpt_path=ckpt_path,
        hparams_path=hparams_path,
        device=device,
        batch_size=batch_size,
        datasets=[pair for pair in dataset_pairs if pair[1] in pending_names],
        skip_if_exists=skip_if_exists,
    )


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Ensure MolFormer embeddings via MolTran subprocess"
    )
    parser.add_argument("--data-dir", type=str, required=True)
    parser.add_argument(
        "--ckpt-path",
        type=str,
        default=DEFAULT_CKPT,
        help="MolFormer checkpoint (default: preprocessing/checkpoints/...)",
    )
    parser.add_argument(
        "--hparams-path",
        type=str,
        default=DEFAULT_HPARAMS,
        help="MolFormer hparams.yaml (default: preprocessing/molformer/hparams.yaml)",
    )
    parser.add_argument("--molformer-env", type=str, default=DEFAULT_MOLFORMER_ENV)
    parser.add_argument("--batch-size", type=int, default=32)
    parser.add_argument(
        "--device",
        type=str,
        default="cuda:0",
    )
    parser.add_argument(
        "--datasets",
        nargs="+",
        default=None,
        help="CSV:PT pairs, e.g. train_set.csv:train_emb.pt",
    )
    parser.add_argument(
        "--skip-if-exists",
        dest="skip_if_exists",
        action="store_true",
        default=True,
    )
    parser.add_argument(
        "--no-skip-if-exists",
        dest="skip_if_exists",
        action="store_false",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    if args.datasets:
        dataset_pairs = [tuple(item.split(":")) for item in args.datasets]
    else:
        dataset_pairs = DEFAULT_TRAIN_DATASETS

    ensure_embeddings(
        data_dir=args.data_dir,
        ckpt_path=args.ckpt_path,
        hparams_path=args.hparams_path,
        molformer_env=args.molformer_env,
        device=args.device,
        batch_size=args.batch_size,
        datasets=dataset_pairs,
        skip_if_exists=args.skip_if_exists,
    )
    print("All datasets processed.")


if __name__ == "__main__":
    main()
